- Dockerfile
- package.json
Fix issue where we could not see the Vue page and also remove unnecessary cruft.
> Mattcs fix dev env

- .github/workflows/terraform-apply.yml
- .github/workflows/terraform-fmt.yml
- .github/workflows/terraform-plan.yml
- .github/workflows/terraform-validate.yml
- .vscode/extensions.json
This adds a few presubmit checks for Terraform changes and sets up automatic apply of said changes upon submission to `main`. This was tested in #8.
It also adds the Github Actions extension to the recommended list.
> Mattcs terraform GitHub ci

- .gitignore
- infra/.terraform.lock.hcl
- infra/Dockerfile
- infra/infra.tf
- infra/spawscli.sh
Set `main` to be the main development branch and set `latest` to be the main prod branch. This PR will apply those changes to our AWS Amplify infrastructure.
Other changes are improvements to helper scripts.
> Mattcs create dev env

- .github/CODEOWNERS
- .github/workflows/enforce-merges-to-latest.yml
- .gitignore
- infra/.terraform.lock.hcl
- infra/Dockerfile
- infra/infra.tf
- infra/spawscli.sh
This will update `latest` to include the CODEOWNERS file for reviews.
> Push main to latest

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/components/Organization.vue
- frontend/src/components/Organizations.vue
- frontend/src/main.ts
Adding tabs for navigation; it would be nice to use`#anchor` links in the URI to be able to navigate to each tab from a URI. 
Installing Babel seemed to be required for this change.
> show organizations; adding navigation tabs

- frontend/src/components/Organizations.vue
- infra/infra.tf
- replace gist with google sheets
- use environment variable for sheet id
> replace GH gist with google sheet

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/components/Woman.vue
- frontend/src/components/Women.vue
- frontend/src/main.ts
https://github.com/Spelman-College/spelman-dashboard/issues/51
Content loaded from this [sheet](https://docs.google.com/spreadsheets/d/1FPL8Jhyv98fOOlfwMcVCApxX_CAYl5vWd1ODdZDk_3k/edit#gid=0)
[Screencast from 2023-07-17 12-24-37.webm](https://github.com/Spelman-College/spelman-dashboard/assets/51137263/1832ea80-57d5-4326-ad08-b6d6cfb444eb)
> show cards, including an image in each

- frontend/babel.config.js
- frontend/jest.config.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/queries/dcids.ts
- frontend/src/queries/query.spec.ts
- frontend/src/queries/query.ts
- frontend/src/queries/sets.spec.ts
- frontend/src/queries/sets.ts
See the demo: https://github.com/Spelman-College/spelman-dashboard/pull/60
- adding query logic
- creates an index(an array) of dcids using inferred dimensions and inferred categories
- categories and dimensions must be known ahead of time
- for a given query (1 or more categories, and 1 or more dimenions per category) create the cartesian product of category/dimension scan the dcid index to acquire each relevant dcid string.
- add Jest testing framework
> Query tools

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/DataDashboard.vue
- frontend/src/components/PlotFigure.vue
- frontend/src/components/data/Demo.vue
- frontend/src/components/data/PlotFigure.vue
- frontend/src/data/dc/client.ts
- frontend/src/data/demo/README.md
- frontend/src/data/demo/plot.ts
- adding the [Plot](https://observablehq.com/product/plot) library
- abstract the dataviz to a component referring to it's respective dataset under the `components/data` dir
- more to be done here- move the dataset title and filter components as well
TODO: 
- move all dataset text and query logic to it's own component.
- add other category filters
- compare categories to each other
> Observable plot demo

- frontend/src/data/queries/import.md
- frontend/src/data/queries/scripts/load_ts.py
adding helper script for importing DCIDs from a CSV.
> add import script

- frontend/public/homepage.css
- frontend/src/router/index.ts
- frontend/src/views/HomeView.vue
- frontend/src/views/StoriesView.vue
**Note:** This PR should not be merged until after #74.
Creates the stories page and adds link to it from the homepage.
> Mattcs frontend stories

- frontend/package-lock.json
- frontend/public/homepage.css
- frontend/src/router/index.ts
- frontend/src/views/AboutView.vue
- frontend/src/views/ContactView.vue
- frontend/src/views/Header.vue
Does not include routing for resources page as Matt is working on this page in parallel.
> Add header routing

- frontend/src/views/Footer.vue
- frontend/src/views/Header.vue
> [XS] Add cursor hover to header/footer links

- frontend/src/components/DataDashboard.vue
- frontend/src/components/data/DatasetSelector.vue
- frontend/src/home/DataDashboard.vue
- frontend/src/main.ts
- frontend/src/views/DataDashboard.vue
> add data selector component to data dashboard view

- frontend/index.html
- frontend/src/components/DataDashboardExploreCard.vue
- frontend/src/router/index.ts
- frontend/src/views/DataDashboardExploreView.vue
Adds the initial data dashboard view.
Remaining todos:
* Add filter sidebar when filter button is clicked
* Update how cards are scrolled depending on UX's intended design
> Add initial data dashboard view

- frontend/src/components/Dropdown.vue
- frontend/src/components/FilterChip.vue
- frontend/src/views/DataDashboardView.vue
Adds a dropdown for filter chips with the filter options. Known issue: #130 
Can select options:
Applied settings show in chip:
Case-insensitive search:
> Mattcs dd chip dropdown

- frontend/src/views/dataDashboardViews/DDWelcomeView.vue
AWS deployment: ![image](https://github.com/Spelman-College/spelman-dashboard/assets/13266735/7b369685-0cc7-47a1-8a3a-f128a14630af)
> [Fix the build] - relative image path

- frontend/src/components/ClickawayDetection.vue
- frontend/src/components/Dropdown.vue
- frontend/src/components/FilterChip.vue
Dialogs now close when clicking away. Closes #130
> Add clickaway detection

- frontend/src/components/data/DatasetSelector.vue
- frontend/src/components/data/Demo.vue
- frontend/src/components/data/PresetExploreSelector.vue
- frontend/src/data/demo/ui.ts
- frontend/src/data/queries/ui.ts
Ensure at least 1 multi-select value is selected in the dropdown. 
Another option would be to make the 'options' in the multiselect a ref and when we detect a single element, set a key in the last option object as [optionDisabled](https://primevue.org/multiselect/#api.multiselect.props.optionDisabled)
- fixes a bug in the dataset selector
- adds the color domain from the figma mock
> prevent < 1 multiselect value

- frontend/src/components/dashboard/DatasetSelector.vue
- frontend/src/components/dashboard/FilterChip.vue
- frontend/src/components/dashboard/data/Demo.vue
- frontend/src/data/demo/ui.ts
- frontend/src/data/queries/ui.ts
- frontend/src/router/index.ts
Update filter components to use styled filters. 
See [/data-dashboard/explore/demo](http://localhost:8080/data-dashboard/explore/demo) for current state
TODO in other PRs
- style plot component
- filters' z-index
- filters should close and open like a native HTML multiselect element
> use styled filters

- .github/workflows/prettier-format.yml
This will not run until a file in src is changed. I'll force a change in a follow-up PR to run the formatter on everything.
> Add github action to autoformat code

- frontend/src/home/Splash.vue
- frontend/src/views/Header.vue
Fix the links for the entry points to Data Dashboard in the Header and Homepage Splash.
> bug fix - update links to data dashboard with new routing name

- frontend/src/components/dashboard/DatasetSelector.vue
- frontend/src/router/index.ts
- frontend/src/views/DataDashboardView.vue
Set the default page for the data dashboard to the help screen.
> Mattcs set dd default page 2

- frontend/src/data/demo/query.spec.ts
> Demo tests use constants

- frontend/src/components/dashboard/CompareRadio.vue
- frontend/src/components/dashboard/DataDashboard.vue
- frontend/src/components/dashboard/data/Demo.vue
this will make it easier to add compare radio buttons on dashboards
> factor out radio button compare component

- frontend/src/components/dashboard/DataDashboard.vue
- frontend/src/components/dashboard/FilterChip.vue
- frontend/src/components/dashboard/data/Ipeds_318_45.vue
- frontend/src/data/demo/ui.ts
- frontend/src/data/ipeds_318_45/categories/values.ts
- frontend/src/data/ipeds_318_45/query/values.spec.ts
- frontend/src/data/ipeds_318_45/query/values.ts
- frontend/src/data/ipeds_318_45/ui/values.ts
- frontend/src/data/queries/dcid.spec.ts
- frontend/src/data/queries/dcid.ts
- frontend/src/data/queries/dimensions.ts
- frontend/src/data/queries/query.ts
- frontend/src/data/queries/scripts/query_dcid.sh
- frontend/src/data/queries/ui.ts
This also adds the ability to replace an explicitly given summary dimension within a DCID category. 
CSS needs help but we'll do that in another PR. 
TODO in another PR:
- refactor compare radio buttons
- move CSS to parent so all dashboards have the same styling.
> Vue component for table #1

- frontend/src/data/queries/ui.ts
> fix race condition

- frontend/src/components/dashboard/data/Demo.vue
- frontend/src/components/dashboard/data/Ipeds_318_45.vue
- frontend/src/components/dashboard/data/Nsf23300_1_10.vue
- frontend/src/data/nsf23300_1_10/query.ts
- frontend/src/data/queries/ui.ts
https://github.com/Spelman-College/spelman-dashboard/issues/190
> factor out renderCategory for re-use

- frontend/src/components/dashboard/DatasetSelector.vue
- frontend/src/data/demo/ui.ts
- frontend/src/data/ipeds_318_45/ui/values.ts
- frontend/src/data/nsf23300_1_10/ui.ts
DONE in this PR:
- Renaming datasets in dropdown as per Figma mocks
- update dropdown formatting as per Figma mocks
Before: dataset name + formatting
After: dataset name + formatting
> Dropdown formatting fix

- frontend/src/components/dashboard/data/Ipeds_318_45.vue
- frontend/src/components/dashboard/data/Nsf23300_1_10.vue
> Reset filters when changing domain

- frontend/src/components/dashboard/data/Demo.vue
- frontend/src/components/dashboard/data/Ipeds_318_45.vue
- frontend/src/components/dashboard/data/Nsf23300_1_10.vue
- frontend/src/data/queries/ui.ts
remove cruft; fix error message
> some fixes

- frontend/src/components/dashboard/FilterChip.vue
> Add warning if user tries to deselect all filters
